In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
from google.colab import files
uploaded=files.upload()

Saving medical_insurance.csv to medical_insurance.csv

In [8]:
df = pd.read_csv("/content/medical_insurance.csv")

In [9]:
df.shape

(100000, 54)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 54 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   sex                          100000 non-null  object
 3   region                       100000 non-null  object
 4   urban_rural                  100000 non-null  object
 5   income                       100000 non-null  float64
 6   education                    100000 non-null  object
 7   marital_status               100000 non-null  object
 8   employment_status            100000 non-null  object
 9   household_size               100000 non-null  int64
 10  dependents                   100000 non-null  int64
 11  bmi                          100000 non-null  float64
 12  smoker                       100000 non-null  object
 13  alcohol_freq                 69917 non-null   object
 14  visits_last_year             100000 non-null  int64
 15  hospitalizations_last_3yrs   100000 non-null  int64
 16  days_hospitalized_last_3yrs  100000 non-null  int64
 17  medication_count             100000 non-null  int64
 18  systolic_bp                  100000 non-null  float64
 19  diastolic_bp                 100000 non-null  float64
 20  ldl                          100000 non-null  float64
 21  hba1c                        100000 non-null  float64
 22  plan_type                    100000 non-null  object
 23  network_tier                 100000 non-null  object
 24  deductible                   100000 non-null  int64
 25  copay                        100000 non-null  int64
 26  policy_term_years            100000 non-null  int64
 27  policy_changes_last_2yrs     100000 non-null  int64
 28  provider_quality             100000 non-null  float64
 29  risk_score                   100000 non-null  float64
 30  annual_medical_cost          100000 non-null  float64
 31  annual_premium               100000 non-null  float64
 32  monthly_premium              100000 non-null  float64
 33  claims_count                 100000 non-null  int64
 34  avg_claim_amount             100000 non-null  float64
 35  total_claims_paid            100000 non-null  float64
 36  chronic_count                100000 non-null  int64
 37  hypertension                 100000 non-null  int64
 38  diabetes                     100000 non-null  int64
 39  asthma                       100000 non-null  int64
 40  copd                         100000 non-null  int64
 41  cardiovascular_disease       100000 non-null  int64
 42  cancer_history               100000 non-null  int64
 43  kidney_disease               100000 non-null  int64
 44  liver_disease                100000 non-null  int64
 45  arthritis                    100000 non-null  int64
 46  mental_health                100000 non-null  int64
 47  proc_imaging_count           100000 non-null  int64
 48  proc_surgery_count           100000 non-null  int64
 49  proc_physio_count            100000 non-null  int64
 50  proc_consult_count           100000 non-null  int64
 51  proc_lab_count               100000 non-null  int64
 52  is_high_risk                 100000 non-null  int64
 53  had_major_procedure          100000 non-null  int64
dtypes: float64(13), int64(31), object(10)
memory usage: 41.2+ MB

In [11]:
df.isnull().sum()

person_id                          0
age                                0
sex                                0
region                             0
urban_rural                        0
income                             0
education                          0
marital_status                     0
employment_status                  0
household_size                     0
dependents                         0
bmi                                0
smoker                             0
alcohol_freq                   30083
visits_last_year                   0
hospitalizations_last_3yrs         0
days_hospitalized_last_3yrs        0
medication_count                   0
systolic_bp                        0
diastolic_bp                       0
ldl                                0
hba1c                              0
plan_type                          0
network_tier                       0
deductible                         0
copay                              0
policy_term_years                  0
policy_changes_last_2yrs           0
provider_quality                   0
risk_score                         0
annual_medical_cost                0
annual_premium                     0
monthly_premium                    0
claims_count                       0
avg_claim_amount                   0
total_claims_paid                  0
chronic_count                      0
hypertension                       0
diabetes                           0
asthma                             0
copd                               0
cardiovascular_disease             0
cancer_history                     0
kidney_disease                     0
liver_disease                      0
arthritis                          0
mental_health                      0
proc_imaging_count                 0
proc_surgery_count                 0
proc_physio_count                  0
proc_consult_count                 0
proc_lab_count                     0
is_high_risk                       0
had_major_procedure                0
dtype: int64

In [12]:
df.drop(columns=[
    'person_id',
    'urban_rural',
    'education',
    'marital_status',
    'employment_status',
    'household_size',
    'dependents',
    'copay',
    'policy_term_years',
    'policy_changes_last_2yrs',
    'annual_premium',
    'monthly_premium',
    'claims_count',
    'avg_claim_amount',
    'total_claims_paid',
    'visits_last_year',
    'hospitalizations_last_3yrs',
    'days_hospitalized_last_3yrs',
    'medication_count',
    'proc_imaging_count',
    'proc_surgery_count',
    'proc_physio_count',
    'proc_consult_count',
    'proc_lab_count',
    'had_major_procedure',
    'copd',
    'cancer_history',
    'kidney_disease',
    'liver_disease',
    'arthritis',
    'mental_health',
    'diastolic_bp',
    'hba1c',
    'is_high_risk'
], inplace=True)

In [13]:
df.head()

,age,sex,region,income,bmi,smoker,alcohol_freq,systolic_bp,ldl,plan_type,network_tier,deductible,provider_quality,risk_score,annual_medical_cost,chronic_count,hypertension,diabetes,asthma,cardiovascular_disease
0,52,Female,North,22700.0,27.4,Never,NaN,121.0,123.8,PPO,Bronze,1000,3.73,0.5714,6938.06,1,0,0,0,0
1,79,Female,North,12800.0,26.6,Never,Weekly,131.0,97.3,POS,Gold,1000,3.10,1.0000,1632.61,2,0,0,0,0
2,68,Male,North,40700.0,31.5,Never,NaN,160.0,129.5,HMO,Platinum,500,3.90,1.0000,7661.01,3,1,0,0,0
3,15,Male,North,15600.0,31.6,Never,NaN,104.0,160.3,HMO,Silver,500,3.89,0.2857,5130.27,1,0,1,0,0
4,53,Male,Central,89600.0,30.5,Never,Daily,136.0,171.0,POS,Platinum,500,3.90,0.8681,1700.73,2,1,0,0,0

In [14]:
df.shape

(100000, 20)

In [15]:
df['alcohol_freq'].fillna(df['alcohol_freq'].mode()[0], inplace=True)
df.isnull().sum()

/tmp/ipykernel_16432/4126724044.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['alcohol_freq'].fillna(df['alcohol_freq'].mode()[0], inplace=True)

age                       0
sex                       0
region                    0
income                    0
bmi                       0
smoker                    0
alcohol_freq              0
systolic_bp               0
ldl                       0
plan_type                 0
network_tier              0
deductible                0
provider_quality          0
risk_score                0
annual_medical_cost       0
chronic_count             0
hypertension              0
diabetes                  0
asthma                    0
cardiovascular_disease    0
dtype: int64

In [16]:
def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif bmi < 25:
        return "Normal"
    elif bmi < 30:
        return "Overweight"
    else:
        return "Obese"

df['bmi_category'] = df['bmi'].apply(bmi_category)

In [17]:
df['health_risk'] = (
    df['hypertension'] +
    df['diabetes'] +
    df['cardiovascular_disease']
)

In [18]:
def age_group(age):
    if age < 30:
        return "Young"
    elif age < 50:
        return "Middle"
    else:
        return "Senior"

df['age_group'] = df['age'].apply(age_group)

In [19]:
df['high_income'] = np.where(df['income'] > df['income'].median(), 1, 0)

In [20]:
df.head()

,age,sex,region,income,bmi,smoker,alcohol_freq,systolic_bp,ldl,plan_type,...,annual_medical_cost,chronic_count,hypertension,diabetes,asthma,cardiovascular_disease,bmi_category,health_risk,age_group,high_income
0,52,Female,North,22700.0,27.4,Never,Occasional,121.0,123.8,PPO,...,6938.06,1,0,0,0,0,Overweight,0,Senior,0
1,79,Female,North,12800.0,26.6,Never,Weekly,131.0,97.3,POS,...,1632.61,2,0,0,0,0,Overweight,0,Senior,0
2,68,Male,North,40700.0,31.5,Never,Occasional,160.0,129.5,HMO,...,7661.01,3,1,0,0,0,Obese,1,Senior,1
3,15,Male,North,15600.0,31.6,Never,Occasional,104.0,160.3,HMO,...,5130.27,1,0,1,0,0,Obese,1,Young,0
4,53,Male,Central,89600.0,30.5,Never,Daily,136.0,171.0,POS,...,1700.73,2,1,0,0,0,Obese,1,Senior,1

In [21]:
df.shape

(100000, 24)

In [22]:
X=df.drop("annual_medical_cost",axis=1)
y=df["annual_medical_cost"]
X=pd.get_dummies(X,drop_first=True)

In [23]:
from sklearn.ensemble import IsolationForest
iso=IsolationForest(contamination=0.02,
                    random_state=42)
mask=iso.fit_predict(X)
X=X[mask==1]
y=y[mask==1]

In [24]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
X,
y,
test_size=0.2,
random_state=42)

In [25]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor(
    n_estimators=500,
    max_depth=20,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train,y_train)

rf_pred=rf.predict(X_test)

In [ ]:
importance=pd.DataFrame({

"Feature":X.columns,

"Importance":rf.feature_importances_

})

importance=importance.sort_values(

by="Importance",

ascending=False)

print(importance.head(20))

In [29]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

import numpy as np

print("Random Forest")

print("R2 :",r2_score(y_test,rf_pred))

print("MAE :",mean_absolute_error(y_test,rf_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,rf_pred)))

print()

Random Forest
R2 : 0.09169508001731397
MAE : 1866.2137653904945
RMSE : 2961.166058409741

In [30]:
sample=X_test.iloc[[0]]

prediction=xgb.predict(sample)

print("Actual Cost :",y_test.iloc[0])

print("Predicted Cost :",prediction[0])

Actual Cost : 1649.39
Predicted Cost : 1892.1599